### ISSUE TITLE
FirewallRuleSet preauthenticated-users: "nat" table is not intended for filtering

### ISSUE THREAD

**Issue by maxguru** [nodogsplash/nodogsplash#67]
I am using version 0.9_beta9.9.8 on OpenWrt Barrier Breaker.

I have the following in nodogsplash.conf, FirewallRuleSet preauthenticated-users block,

```
FirewallRule allow tcp port 53
FirewallRule allow udp port 53
FirewallRule drop
```

The startup command is as follows,

/usr/bin/nodogsplash -s -f -d 5

I get the following output,

[5][Wed Apr 15 23:52:54 2015][3778](src/gateway.c:339) Reading and validating configuration file /etc/nodogsplash/nodogsplash.conf
[5][Wed Apr 15 23:52:54 2015][3778](src/gateway.c:347) Initializing signal handlers
[5][Wed Apr 15 23:52:54 2015][3778](src/gateway.c:245) Created web server on 192.168.1.1:2050
[5][Wed Apr 15 23:52:54 2015][3778](src/gateway.c:271) Initializing firewall rules
iptables v1.4.21: 
The "nat" table is not intended for filtering, the use of DROP is therefore inhibited.

Try `iptables -h' or 'iptables --help' for more information.
[3][Wed Apr 15 23:52:54 2015][3778](src/fw_iptables.c:180) Nonzero exit status 2 from command: iptables -t nat -A ndsOUT -d 0.0.0.0/0 -j DROP
[3][Wed Apr 15 23:52:54 2015][3778](src/gateway.c:273) Error initializing firewall rules! Cleaning up
[3][Wed Apr 15 23:52:54 2015][3778](src/gateway.c:275) Exiting because of error initializing firewall rules

**Comment by mwarning** [comment]
This is not realy my area of expertise. Maybe someone else can comment und this. Or you offer a fix. ;-)

**Comment by 4L3Xx** [comment]
By the way, my testing shows that pre-authenticated users are able to bypass the captive portal due to the "EmptyRuleSetPolicy preauthenticated-users block" thing not working at all.

**Comment by 4L3Xx** [comment]
My knowledge of linux networking internals is very limited.  However, I do want to know why this is necessary,

# FirewallRuleSet: preauthenticated-users
#
# Control access for users before authentication.
# These rules are inserted in the PREROUTING chain
# of the router's nat table, and in the
# FORWARD chain of the router's filter table.

Why also into "the PREROUTING chain of the router's nat table?"  It seems to me that this is where the problem is.

**Comment by bluewavenet** [comment]
I had the problem with the version included with Barrier Breaker 14.07 ie preauth clients can bypass entirely on ANY port other than 80. 
I found this was a known problem and has now been fixed.
Tried the version included with ChaosCalmer 15.05 rc2 (nds 0.9_b9.9.9) and it now works perfectly in BB 14.07.
